### ISSUE TITLE
张百琰、詹佳佳、覃诗语、郑涤非小组

### ISSUE THREAD

**Issue by GitHubZian** [QZHY-HTX/QZOI-Hackathon#1]
# 小组成员：
1.张百琰 https://github.com/ZBYMM；
2.詹佳佳 https://github.com/297jia；
3.覃诗语 https://github.com/Songqvq；
4.郑涤非 https://github.com/GitHubZian；
# 小组赛道：
微信小程序

**Comment by QZHY-HTX** [comment]
你们的项目源码在哪啊
