### ISSUE TITLE
微小五人组

### ISSUE THREAD

**Issue by FJ-FTH** [QZHY-HTX/QZOI-Hackathon#2]
赛道：
微信小程序。
成员：
移动互联应用技术 222 张威；
移动互联应用技术 222 王志阳；
移动互联 应用技术222 颜圣炜；
计算机应用技术 225 陈红；
计算机应用技术 225 范庭华。

**Comment by QZHY-HTX** [comment]
加油呐

**Comment by FJ-FTH** [comment]
[Uploading 位置预约…]()

**Comment by FJ-FTH** [comment]
[Uploading 位置预约.zip…]()
